name: Minify CSS & JS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Minify
        run: |
          npm install postcss-cli cssnano terser
          npx postcss public/style.css --use cssnano --replace
          npx terser public/script.js -o public/script.js -c -m --ecma 2020

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated: Minify CSS and JS'
          file_pattern: 'public/style.css public/script.js'